### ISSUE TITLE
Compound type support

### ISSUE THREAD

**Issue by rene-aguirre** [aldanor/hdf5-rs#12]
Hello @aldanor, currently compound types are not supported (H5T_COMPOUND).

Do you currently have any plans for supporting them?

**Comment by aldanor** [comment]
Yes, I have big plans :) See this branch: https://github.com/aldanor/hdf5-rs/tree/feature/types

There's a little bit left to finish it (+ndarray integration, +proper unicode handling) which I plan to finish before New Year, but probably not much sooner.

**Comment by aldanor** [comment]
Usage examples: kind of like this - https://github.com/aldanor/hdf5-rs/blob/feature/types/src/types/h5def.rs#L135

**Comment by aldanor** [comment]
Compound types have been support for a while now through derive proc-macros (see example in README).
